---

- name: Install dependencies needed to install Docker+Docker Compose
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  when: ansible_os_family == 'Debian' #checks facts from managed server and performs task if fact key's value equals to 'Debian'
    
- name: Add Docker GPG key # checks for docker package signatures
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Docker repository # Downloads Docker repository which points where the Docker packages should be downloaded from
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
    state: present
  when: ansible_os_family == 'Debian'

- name: Install Docker 
  apt:
    name:
      - docker-ce # Docker Engine
      - docker-ce-cli
      - containerd.io
    state: present
  when: ansible_os_family == 'Debian'

- name: Install Docker dependencies for RedHat
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  when: ansible_os_family == 'RedHat'

- name: Add Docker repository
  yum_repository:
    name: docker-ce-stable
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: 1
    priority: 1
  when: ansible_os_family == 'RedHat'

- name: Install Docker for RedHat
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  when: ansible_os_family == 'RedHat'

- name: Start and enable Docker service # makes docker work continuously
  systemd:
    name: docker
    state: started # launches Docker service
    enabled: yes
    
    

- name: Install Docker Compose
  remote_user: ubuntu
  get_url: # docker compose is downloaded from url and then it somehow installs itself
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system|lower }}-{{ ansible_machine }}
    dest: /usr/local/bin/docker-compose
    mode: 'u+rx,g+rx'
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

- name: Change owner and group of docker-compose # to make sure file would belong to "docker" group so that user might -->
  file:                                          # --> operate with docker-compose
    path: /usr/local/bin/docker-compose
    owner: root
    group: docker
         

- name: add "ubuntu" user to "docker" group  # to make sure user is in the "doker" group
  user:
    name: "ubuntu"
    groups: "docker"
    append: yes
  become: true 

